### ISSUE TITLE
useEffect cleanup not called

### ISSUE THREAD

**Issue by SirbyAlive** [antoinejaussoin/jooks#1]
### Context

According to the official documentation of [effects with cleanup](https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup), an effect can return a Function that will be used called before the next call of the effect.

This method is called to cleanup the effect on unmount but also to cleanup the effect of the previous render if the dependency changed.
This is useful to cleanup events and references on unmount, or to debounce,  discard or cancel async events that can happen is any order.

### Problems

1. This cleanup is not called by jooks in between effects executions.
2. We miss a way to simulate the `unmount` of the hook to check that our hook is clean.

Cool project nevertheless, very useful to test hooks in a more functional way.

**Comment by antoinejaussoin** [comment]
Very good point, will see how I can deal with this!

**Comment by antoinejaussoin** [comment]
@SirbyAlive : Ok so I made a fix and released a new version. Can you let me know if that works for you? (you can call `await jooks.unmount();` to force calling the cleanup functions).

**Comment by SirbyAlive** [comment]
Hey @antoinejaussoin ,

Thank you for your reactiveness, I updated my tests this morning and it works nicely.
The cleanup is not called in between effects but it is called on `await jooks.unmount();` so we can test that the effect is correctly cleaned up and from there interpolate that it will be cleaned in between effects in the real environment. So that is good for me.

Thank you!
